language: python
os:
- linux
python:
- '3.7'
install:
- pip install -r requirements.txt
- pip install .
script:
- pytest tests
notifications:
  slack:
    secure: rlLWtxBUFu+o3mCcz1FnKi5Ylmsy9ZtaSG5Ex0c45oZpGWOidRdpoqJqgZO+nBpVgAcmupKmEjRHvOl2waPMgP2Xbyh++FOPCdEM+WB1R4cGPOVrAv+8H+m3A6oKSX+fRXjZM5rqEDgaV4LVlTQPkFfdcGX+tSwrlpHV5xeMRp2hhRJ4LZ/VvnzV/Y7B+Z1wSFyidiOflhGwzdp2todqIFt87ZpfJ7FEj3oPBtnvquGY0Yq3GoMgBDcRddFdo7UMk582H2FyEUdOk6v7Qnie9BBooSaA9tPlY4m5rBzD/hP47qXo3x7mOZaGQnl/TeItIVe9eJFesANStQKevgkeg/rK/iq4xM+7dMa+SQIu2AOShF1auwnVN/2nKPUlbgV4Idi3CQb6uH9lcFp7p9gRA3TXBj4+VUsP/74PMC2blR07G7s/r9+QGpYQLD+5ODZ9wNG9K+sOCB18hs3ZeuY94B+GDTWnsjZtFsV73OLy/+EfSyY4W9R+Vv5KdDDVd4ldkVx8QPQNSljska90GbA1M5Rspj78FdLDvCz4TqH5AsqavFmSyqshRrICVFJQS1H2z12kF4K5SKMbxcDMWYxqDUK34cqjefXfz2HPrJWtDCN23jFxa+4OBplMoUJxow4Al0Qu3SZnDKnRIoM17ILxb75mJODYo6f5Wd4TLhrqgpI=

env:
  CLUSTERPASS:
    secure: "XTDi3iqoNupGVFG+l72znejmpHiMHN7NdElU8v2TrXmr+h6TlkYWi06r9A2GCs1p13O4CgKl4WYD/hZKO51I26H/SiR5n5fCs9tnu3sEhvGcevAX/Gux7FtE2iu7xV1fgd6Es3DJ8uzqhw6yVI/VOtQjEqujgdD69OPzziyjM6DASgH8jOxKjQyQIsMA7plXD7foDR+++4kNbjb9ZLplOGLOD8umnvYJQyqvjr/zopcAWhvNGxUth66j2A9+lHLtoVtCYC9AsD7+MxDVxbEEalPMmE0Mv6l7KFwSs/TmiMs76fcK1T75lnooeNT3gChauOzjIrqw+oJxeIC+SvfZYTUV3EZzPuPmWWhUEvpiuSdymwJlKLJRpxpOP3ISWpBxtvd5KA8CVC8HyQMCD/JnQADxA6EIrDBJjvDNgdPyeYR6bwcMt1m8ndAu26WBzfMSx6Mw/hghCwCnnfXuukHxHpZPu8OJ+IpspIQ050VXeD0VusmWGp97N/n2lRNUJk80OSgePUtDkSrLpKhdhGSzN4rkg4uVuxw29UAb8GmzHdFVg1V5ZnaWWvV01LvSUe+JQOTBcGRMdGTeoPPSug8f2cDXHAdFQVPi6XfB3W2Ddobb4ZMlgrl5KX7Azxuk08DyLm+YXIyRmOdUjaC4a7G1PLBfpmoJK2G6MRUuzDzlpBg="
