#!/bin/bash
#SBATCH -N 1
#SBATCH -c 16
#SBATCH -t 00:60:00
#SBATCH -J auto_cluster_job
#SBATCH -o auto_cluster_job.out.%j
#SBATCH -e auto_cluster_job.er.%j
#SBATCH --mem=100000
##SBATCH --mail-type=END
##SBATCH --mail-user=

export PATH=${USERAPPL}/my_python/bin:$PATH
export PYTHONPATH=${USERAPPL}/my_python/lib/python2.7/site-packages:$PYTHONPATH

module purge
module load gcc/4.8.2
module list

set -xe

cd ${SLURM_SUBMIT_DIR:-.}
pwd

