#ifndef _INCLUDED_synapses_34_pre_group_variable_set_conditional_codeobject
#define _INCLUDED_synapses_34_pre_group_variable_set_conditional_codeobject

#include "objects.h"

void _run_synapses_34_pre_group_variable_set_conditional_codeobject();


#endif
