
#ifndef _BRIAN_OBJECTS_H
#define _BRIAN_OBJECTS_H

#include "synapses_classes.h"
#include "brianlib/clocks.h"
#include "brianlib/dynamic_array.h"
#include "brianlib/stdint_compat.h"
#include "network.h"
#include "randomkit.h"
#include<vector>


namespace brian {

// In OpenMP we need one state per thread
extern std::vector< rk_state* > _mersenne_twister_states;

//////////////// clocks ///////////////////
extern Clock defaultclock;

//////////////// networks /////////////////
extern Network magicnetwork;

//////////////// dynamic arrays ///////////
extern std::vector<int32_t> _dynamic_array_spikegeneratorgroup__timebins;
extern std::vector<int32_t> _dynamic_array_spikegeneratorgroup_neuron_index;
extern std::vector<int32_t> _dynamic_array_spikegeneratorgroup_spike_number;
extern std::vector<double> _dynamic_array_spikegeneratorgroup_spike_time;
extern std::vector<int32_t> _dynamic_array_spikemonitor_1_i;
extern std::vector<double> _dynamic_array_spikemonitor_1_t;
extern std::vector<int32_t> _dynamic_array_spikemonitor_2_i;
extern std::vector<double> _dynamic_array_spikemonitor_2_t;
extern std::vector<int32_t> _dynamic_array_spikemonitor_3_i;
extern std::vector<double> _dynamic_array_spikemonitor_3_t;
extern std::vector<int32_t> _dynamic_array_spikemonitor_4_i;
extern std::vector<double> _dynamic_array_spikemonitor_4_t;
extern std::vector<int32_t> _dynamic_array_spikemonitor_5_i;
extern std::vector<double> _dynamic_array_spikemonitor_5_t;
extern std::vector<int32_t> _dynamic_array_spikemonitor_i;
extern std::vector<double> _dynamic_array_spikemonitor_t;
extern std::vector<int32_t> _dynamic_array_synapses_10__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_10__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_10_delay;
extern std::vector<double> _dynamic_array_synapses_10_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_10_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_10_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_10_R;
extern std::vector<double> _dynamic_array_synapses_10_wght;
extern std::vector<int32_t> _dynamic_array_synapses_11__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_11__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_11_delay;
extern std::vector<double> _dynamic_array_synapses_11_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_11_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_11_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_11_R;
extern std::vector<double> _dynamic_array_synapses_11_wght;
extern std::vector<int32_t> _dynamic_array_synapses_12__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_12__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_12_delay;
extern std::vector<double> _dynamic_array_synapses_12_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_12_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_12_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_12_R;
extern std::vector<double> _dynamic_array_synapses_12_wght;
extern std::vector<int32_t> _dynamic_array_synapses_13__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_13__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_13_delay;
extern std::vector<double> _dynamic_array_synapses_13_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_13_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_13_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_13_R;
extern std::vector<double> _dynamic_array_synapses_13_wght;
extern std::vector<int32_t> _dynamic_array_synapses_14__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_14__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_14_delay;
extern std::vector<double> _dynamic_array_synapses_14_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_14_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_14_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_14_R;
extern std::vector<double> _dynamic_array_synapses_14_wght;
extern std::vector<int32_t> _dynamic_array_synapses_15__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_15__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_15_delay;
extern std::vector<double> _dynamic_array_synapses_15_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_15_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_15_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_15_R;
extern std::vector<double> _dynamic_array_synapses_15_wght;
extern std::vector<int32_t> _dynamic_array_synapses_16__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_16__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_16_delay;
extern std::vector<double> _dynamic_array_synapses_16_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_16_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_16_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_16_R;
extern std::vector<double> _dynamic_array_synapses_16_wght;
extern std::vector<int32_t> _dynamic_array_synapses_17__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_17__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_17_delay;
extern std::vector<double> _dynamic_array_synapses_17_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_17_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_17_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_17_R;
extern std::vector<double> _dynamic_array_synapses_17_wght;
extern std::vector<int32_t> _dynamic_array_synapses_18__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_18__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_18_delay;
extern std::vector<double> _dynamic_array_synapses_18_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_18_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_18_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_18_R;
extern std::vector<double> _dynamic_array_synapses_18_wght;
extern std::vector<int32_t> _dynamic_array_synapses_19__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_19__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_19_delay;
extern std::vector<double> _dynamic_array_synapses_19_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_19_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_19_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_19_R;
extern std::vector<double> _dynamic_array_synapses_19_wght;
extern std::vector<int32_t> _dynamic_array_synapses_1__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_1__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_1_delay;
extern std::vector<double> _dynamic_array_synapses_1_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_1_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_1_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_1_R;
extern std::vector<double> _dynamic_array_synapses_1_wght;
extern std::vector<int32_t> _dynamic_array_synapses_20__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_20__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_20_delay;
extern std::vector<double> _dynamic_array_synapses_20_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_20_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_20_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_20_R;
extern std::vector<double> _dynamic_array_synapses_20_wght;
extern std::vector<int32_t> _dynamic_array_synapses_21__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_21__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_21_delay;
extern std::vector<double> _dynamic_array_synapses_21_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_21_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_21_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_21_R;
extern std::vector<double> _dynamic_array_synapses_21_wght;
extern std::vector<int32_t> _dynamic_array_synapses_22__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_22__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_22_delay;
extern std::vector<double> _dynamic_array_synapses_22_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_22_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_22_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_22_R;
extern std::vector<double> _dynamic_array_synapses_22_wght;
extern std::vector<int32_t> _dynamic_array_synapses_23__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_23__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_23_delay;
extern std::vector<double> _dynamic_array_synapses_23_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_23_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_23_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_23_R;
extern std::vector<double> _dynamic_array_synapses_23_wght;
extern std::vector<int32_t> _dynamic_array_synapses_24__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_24__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_24_delay;
extern std::vector<double> _dynamic_array_synapses_24_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_24_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_24_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_24_R;
extern std::vector<double> _dynamic_array_synapses_24_wght;
extern std::vector<int32_t> _dynamic_array_synapses_25__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_25__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_25_delay;
extern std::vector<double> _dynamic_array_synapses_25_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_25_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_25_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_25_R;
extern std::vector<double> _dynamic_array_synapses_25_wght;
extern std::vector<int32_t> _dynamic_array_synapses_26__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_26__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_26_delay;
extern std::vector<double> _dynamic_array_synapses_26_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_26_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_26_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_26_R;
extern std::vector<double> _dynamic_array_synapses_26_wght;
extern std::vector<int32_t> _dynamic_array_synapses_27__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_27__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_27_delay;
extern std::vector<double> _dynamic_array_synapses_27_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_27_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_27_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_27_R;
extern std::vector<double> _dynamic_array_synapses_27_wght;
extern std::vector<int32_t> _dynamic_array_synapses_28__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_28__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_28_delay;
extern std::vector<double> _dynamic_array_synapses_28_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_28_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_28_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_28_R;
extern std::vector<double> _dynamic_array_synapses_28_wght;
extern std::vector<int32_t> _dynamic_array_synapses_29__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_29__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_29_delay;
extern std::vector<double> _dynamic_array_synapses_29_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_29_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_29_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_29_R;
extern std::vector<double> _dynamic_array_synapses_29_wght;
extern std::vector<int32_t> _dynamic_array_synapses_2__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_2__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_2_delay;
extern std::vector<double> _dynamic_array_synapses_2_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_2_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_2_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_2_R;
extern std::vector<double> _dynamic_array_synapses_2_wght;
extern std::vector<int32_t> _dynamic_array_synapses_30__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_30__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_30_delay;
extern std::vector<double> _dynamic_array_synapses_30_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_30_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_30_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_30_R;
extern std::vector<double> _dynamic_array_synapses_30_wght;
extern std::vector<int32_t> _dynamic_array_synapses_31__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_31__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_31_delay;
extern std::vector<double> _dynamic_array_synapses_31_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_31_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_31_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_31_R;
extern std::vector<double> _dynamic_array_synapses_31_wght;
extern std::vector<int32_t> _dynamic_array_synapses_32__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_32__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_32_delay;
extern std::vector<double> _dynamic_array_synapses_32_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_32_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_32_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_32_R;
extern std::vector<double> _dynamic_array_synapses_32_wght;
extern std::vector<int32_t> _dynamic_array_synapses_33__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_33__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_33_delay;
extern std::vector<double> _dynamic_array_synapses_33_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_33_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_33_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_33_R;
extern std::vector<double> _dynamic_array_synapses_33_wght;
extern std::vector<int32_t> _dynamic_array_synapses_34__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_34__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_34_delay;
extern std::vector<double> _dynamic_array_synapses_34_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_34_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_34_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_34_R;
extern std::vector<double> _dynamic_array_synapses_34_wght;
extern std::vector<int32_t> _dynamic_array_synapses_35__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_35__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_35_delay;
extern std::vector<double> _dynamic_array_synapses_35_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_35_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_35_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_35_R;
extern std::vector<double> _dynamic_array_synapses_35_wght;
extern std::vector<int32_t> _dynamic_array_synapses_36__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_36__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_36_delay;
extern std::vector<double> _dynamic_array_synapses_36_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_36_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_36_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_36_R;
extern std::vector<double> _dynamic_array_synapses_36_wght;
extern std::vector<int32_t> _dynamic_array_synapses_37__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_37__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_37_delay;
extern std::vector<double> _dynamic_array_synapses_37_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_37_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_37_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_37_R;
extern std::vector<double> _dynamic_array_synapses_37_wght;
extern std::vector<int32_t> _dynamic_array_synapses_3__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_3__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_3_delay;
extern std::vector<double> _dynamic_array_synapses_3_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_3_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_3_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_3_R;
extern std::vector<double> _dynamic_array_synapses_3_wght;
extern std::vector<int32_t> _dynamic_array_synapses_4__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_4__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_4_delay;
extern std::vector<double> _dynamic_array_synapses_4_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_4_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_4_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_4_R;
extern std::vector<double> _dynamic_array_synapses_4_wght;
extern std::vector<int32_t> _dynamic_array_synapses_5__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_5__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_5_delay;
extern std::vector<double> _dynamic_array_synapses_5_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_5_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_5_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_5_R;
extern std::vector<double> _dynamic_array_synapses_5_wght;
extern std::vector<int32_t> _dynamic_array_synapses_6__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_6__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_6_delay;
extern std::vector<double> _dynamic_array_synapses_6_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_6_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_6_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_6_R;
extern std::vector<double> _dynamic_array_synapses_6_wght;
extern std::vector<int32_t> _dynamic_array_synapses_7__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_7__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_7_delay;
extern std::vector<double> _dynamic_array_synapses_7_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_7_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_7_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_7_R;
extern std::vector<double> _dynamic_array_synapses_7_wght;
extern std::vector<int32_t> _dynamic_array_synapses_8__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_8__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_8_delay;
extern std::vector<double> _dynamic_array_synapses_8_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_8_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_8_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_8_R;
extern std::vector<double> _dynamic_array_synapses_8_wght;
extern std::vector<int32_t> _dynamic_array_synapses_9__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses_9__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_9_delay;
extern std::vector<double> _dynamic_array_synapses_9_lastupdate;
extern std::vector<int32_t> _dynamic_array_synapses_9_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_9_N_outgoing;
extern std::vector<double> _dynamic_array_synapses_9_R;
extern std::vector<double> _dynamic_array_synapses_9_wght;
extern std::vector<int32_t> _dynamic_array_synapses__synaptic_post;
extern std::vector<int32_t> _dynamic_array_synapses__synaptic_pre;
extern std::vector<double> _dynamic_array_synapses_delay;
extern std::vector<int32_t> _dynamic_array_synapses_N_incoming;
extern std::vector<int32_t> _dynamic_array_synapses_N_outgoing;

//////////////// arrays ///////////////////
extern double *_array_defaultclock_dt;
extern const int _num__array_defaultclock_dt;
extern double *_array_defaultclock_t;
extern const int _num__array_defaultclock_t;
extern int64_t *_array_defaultclock_timestep;
extern const int _num__array_defaultclock_timestep;
extern int32_t *_array_neurongroup_1__spikespace;
extern const int _num__array_neurongroup_1__spikespace;
extern double *_array_neurongroup_1_ge_a0;
extern const int _num__array_neurongroup_1_ge_a0;
extern double *_array_neurongroup_1_ge_a1;
extern const int _num__array_neurongroup_1_ge_a1;
extern double *_array_neurongroup_1_ge_a2;
extern const int _num__array_neurongroup_1_ge_a2;
extern double *_array_neurongroup_1_ge_basal;
extern const int _num__array_neurongroup_1_ge_basal;
extern double *_array_neurongroup_1_ge_soma;
extern const int _num__array_neurongroup_1_ge_soma;
extern double *_array_neurongroup_1_gealpha_a0;
extern const int _num__array_neurongroup_1_gealpha_a0;
extern double *_array_neurongroup_1_gealpha_a1;
extern const int _num__array_neurongroup_1_gealpha_a1;
extern double *_array_neurongroup_1_gealpha_a2;
extern const int _num__array_neurongroup_1_gealpha_a2;
extern double *_array_neurongroup_1_gealpha_basal;
extern const int _num__array_neurongroup_1_gealpha_basal;
extern double *_array_neurongroup_1_gealpha_soma;
extern const int _num__array_neurongroup_1_gealpha_soma;
extern double *_array_neurongroup_1_gi_a0;
extern const int _num__array_neurongroup_1_gi_a0;
extern double *_array_neurongroup_1_gi_a1;
extern const int _num__array_neurongroup_1_gi_a1;
extern double *_array_neurongroup_1_gi_a2;
extern const int _num__array_neurongroup_1_gi_a2;
extern double *_array_neurongroup_1_gi_basal;
extern const int _num__array_neurongroup_1_gi_basal;
extern double *_array_neurongroup_1_gi_soma;
extern const int _num__array_neurongroup_1_gi_soma;
extern double *_array_neurongroup_1_gialpha_a0;
extern const int _num__array_neurongroup_1_gialpha_a0;
extern double *_array_neurongroup_1_gialpha_a1;
extern const int _num__array_neurongroup_1_gialpha_a1;
extern double *_array_neurongroup_1_gialpha_a2;
extern const int _num__array_neurongroup_1_gialpha_a2;
extern double *_array_neurongroup_1_gialpha_basal;
extern const int _num__array_neurongroup_1_gialpha_basal;
extern double *_array_neurongroup_1_gialpha_soma;
extern const int _num__array_neurongroup_1_gialpha_soma;
extern int32_t *_array_neurongroup_1_i;
extern const int _num__array_neurongroup_1_i;
extern double *_array_neurongroup_1_lastspike;
extern const int _num__array_neurongroup_1_lastspike;
extern char *_array_neurongroup_1_not_refractory;
extern const int _num__array_neurongroup_1_not_refractory;
extern double *_array_neurongroup_1_vm;
extern const int _num__array_neurongroup_1_vm;
extern double *_array_neurongroup_1_vm_a0;
extern const int _num__array_neurongroup_1_vm_a0;
extern double *_array_neurongroup_1_vm_a1;
extern const int _num__array_neurongroup_1_vm_a1;
extern double *_array_neurongroup_1_vm_a2;
extern const int _num__array_neurongroup_1_vm_a2;
extern double *_array_neurongroup_1_vm_basal;
extern const int _num__array_neurongroup_1_vm_basal;
extern double *_array_neurongroup_1_x;
extern const int _num__array_neurongroup_1_x;
extern double *_array_neurongroup_1_y;
extern const int _num__array_neurongroup_1_y;
extern int32_t *_array_neurongroup_2__spikespace;
extern const int _num__array_neurongroup_2__spikespace;
extern double *_array_neurongroup_2_ge_a0;
extern const int _num__array_neurongroup_2_ge_a0;
extern double *_array_neurongroup_2_ge_a1;
extern const int _num__array_neurongroup_2_ge_a1;
extern double *_array_neurongroup_2_ge_a2;
extern const int _num__array_neurongroup_2_ge_a2;
extern double *_array_neurongroup_2_ge_basal;
extern const int _num__array_neurongroup_2_ge_basal;
extern double *_array_neurongroup_2_ge_soma;
extern const int _num__array_neurongroup_2_ge_soma;
extern double *_array_neurongroup_2_gealpha_a0;
extern const int _num__array_neurongroup_2_gealpha_a0;
extern double *_array_neurongroup_2_gealpha_a1;
extern const int _num__array_neurongroup_2_gealpha_a1;
extern double *_array_neurongroup_2_gealpha_a2;
extern const int _num__array_neurongroup_2_gealpha_a2;
extern double *_array_neurongroup_2_gealpha_basal;
extern const int _num__array_neurongroup_2_gealpha_basal;
extern double *_array_neurongroup_2_gealpha_soma;
extern const int _num__array_neurongroup_2_gealpha_soma;
extern double *_array_neurongroup_2_gi_a0;
extern const int _num__array_neurongroup_2_gi_a0;
extern double *_array_neurongroup_2_gi_a1;
extern const int _num__array_neurongroup_2_gi_a1;
extern double *_array_neurongroup_2_gi_a2;
extern const int _num__array_neurongroup_2_gi_a2;
extern double *_array_neurongroup_2_gi_basal;
extern const int _num__array_neurongroup_2_gi_basal;
extern double *_array_neurongroup_2_gi_soma;
extern const int _num__array_neurongroup_2_gi_soma;
extern double *_array_neurongroup_2_gialpha_a0;
extern const int _num__array_neurongroup_2_gialpha_a0;
extern double *_array_neurongroup_2_gialpha_a1;
extern const int _num__array_neurongroup_2_gialpha_a1;
extern double *_array_neurongroup_2_gialpha_a2;
extern const int _num__array_neurongroup_2_gialpha_a2;
extern double *_array_neurongroup_2_gialpha_basal;
extern const int _num__array_neurongroup_2_gialpha_basal;
extern double *_array_neurongroup_2_gialpha_soma;
extern const int _num__array_neurongroup_2_gialpha_soma;
extern int32_t *_array_neurongroup_2_i;
extern const int _num__array_neurongroup_2_i;
extern double *_array_neurongroup_2_lastspike;
extern const int _num__array_neurongroup_2_lastspike;
extern char *_array_neurongroup_2_not_refractory;
extern const int _num__array_neurongroup_2_not_refractory;
extern double *_array_neurongroup_2_vm;
extern const int _num__array_neurongroup_2_vm;
extern double *_array_neurongroup_2_vm_a0;
extern const int _num__array_neurongroup_2_vm_a0;
extern double *_array_neurongroup_2_vm_a1;
extern const int _num__array_neurongroup_2_vm_a1;
extern double *_array_neurongroup_2_vm_a2;
extern const int _num__array_neurongroup_2_vm_a2;
extern double *_array_neurongroup_2_vm_basal;
extern const int _num__array_neurongroup_2_vm_basal;
extern double *_array_neurongroup_2_x;
extern const int _num__array_neurongroup_2_x;
extern double *_array_neurongroup_2_y;
extern const int _num__array_neurongroup_2_y;
extern int32_t *_array_neurongroup_3__spikespace;
extern const int _num__array_neurongroup_3__spikespace;
extern double *_array_neurongroup_3_ge_soma;
extern const int _num__array_neurongroup_3_ge_soma;
extern double *_array_neurongroup_3_gi_soma;
extern const int _num__array_neurongroup_3_gi_soma;
extern int32_t *_array_neurongroup_3_i;
extern const int _num__array_neurongroup_3_i;
extern double *_array_neurongroup_3_lastspike;
extern const int _num__array_neurongroup_3_lastspike;
extern char *_array_neurongroup_3_not_refractory;
extern const int _num__array_neurongroup_3_not_refractory;
extern double *_array_neurongroup_3_vm;
extern const int _num__array_neurongroup_3_vm;
extern double *_array_neurongroup_3_x;
extern const int _num__array_neurongroup_3_x;
extern double *_array_neurongroup_3_y;
extern const int _num__array_neurongroup_3_y;
extern int32_t *_array_neurongroup_4__spikespace;
extern const int _num__array_neurongroup_4__spikespace;
extern double *_array_neurongroup_4_ge_soma;
extern const int _num__array_neurongroup_4_ge_soma;
extern double *_array_neurongroup_4_gi_soma;
extern const int _num__array_neurongroup_4_gi_soma;
extern int32_t *_array_neurongroup_4_i;
extern const int _num__array_neurongroup_4_i;
extern double *_array_neurongroup_4_lastspike;
extern const int _num__array_neurongroup_4_lastspike;
extern char *_array_neurongroup_4_not_refractory;
extern const int _num__array_neurongroup_4_not_refractory;
extern double *_array_neurongroup_4_vm;
extern const int _num__array_neurongroup_4_vm;
extern double *_array_neurongroup_4_x;
extern const int _num__array_neurongroup_4_x;
extern double *_array_neurongroup_4_y;
extern const int _num__array_neurongroup_4_y;
extern int32_t *_array_neurongroup_5__spikespace;
extern const int _num__array_neurongroup_5__spikespace;
extern double *_array_neurongroup_5_ge_soma;
extern const int _num__array_neurongroup_5_ge_soma;
extern double *_array_neurongroup_5_gi_soma;
extern const int _num__array_neurongroup_5_gi_soma;
extern int32_t *_array_neurongroup_5_i;
extern const int _num__array_neurongroup_5_i;
extern double *_array_neurongroup_5_lastspike;
extern const int _num__array_neurongroup_5_lastspike;
extern char *_array_neurongroup_5_not_refractory;
extern const int _num__array_neurongroup_5_not_refractory;
extern double *_array_neurongroup_5_vm;
extern const int _num__array_neurongroup_5_vm;
extern double *_array_neurongroup_5_x;
extern const int _num__array_neurongroup_5_x;
extern double *_array_neurongroup_5_y;
extern const int _num__array_neurongroup_5_y;
extern int32_t *_array_neurongroup__spikespace;
extern const int _num__array_neurongroup__spikespace;
extern double *_array_neurongroup_emit_spike;
extern const int _num__array_neurongroup_emit_spike;
extern int32_t *_array_neurongroup_i;
extern const int _num__array_neurongroup_i;
extern double *_array_neurongroup_x;
extern const int _num__array_neurongroup_x;
extern double *_array_neurongroup_y;
extern const int _num__array_neurongroup_y;
extern int32_t *_array_spikegeneratorgroup__lastindex;
extern const int _num__array_spikegeneratorgroup__lastindex;
extern int32_t *_array_spikegeneratorgroup__period_bins;
extern const int _num__array_spikegeneratorgroup__period_bins;
extern int32_t *_array_spikegeneratorgroup__spikespace;
extern const int _num__array_spikegeneratorgroup__spikespace;
extern int32_t *_array_spikegeneratorgroup_i;
extern const int _num__array_spikegeneratorgroup_i;
extern double *_array_spikegeneratorgroup_period;
extern const int _num__array_spikegeneratorgroup_period;
extern int32_t *_array_spikemonitor_1__source_idx;
extern const int _num__array_spikemonitor_1__source_idx;
extern int32_t *_array_spikemonitor_1_count;
extern const int _num__array_spikemonitor_1_count;
extern int32_t *_array_spikemonitor_1_N;
extern const int _num__array_spikemonitor_1_N;
extern int32_t *_array_spikemonitor_2__source_idx;
extern const int _num__array_spikemonitor_2__source_idx;
extern int32_t *_array_spikemonitor_2_count;
extern const int _num__array_spikemonitor_2_count;
extern int32_t *_array_spikemonitor_2_N;
extern const int _num__array_spikemonitor_2_N;
extern int32_t *_array_spikemonitor_3__source_idx;
extern const int _num__array_spikemonitor_3__source_idx;
extern int32_t *_array_spikemonitor_3_count;
extern const int _num__array_spikemonitor_3_count;
extern int32_t *_array_spikemonitor_3_N;
extern const int _num__array_spikemonitor_3_N;
extern int32_t *_array_spikemonitor_4__source_idx;
extern const int _num__array_spikemonitor_4__source_idx;
extern int32_t *_array_spikemonitor_4_count;
extern const int _num__array_spikemonitor_4_count;
extern int32_t *_array_spikemonitor_4_N;
extern const int _num__array_spikemonitor_4_N;
extern int32_t *_array_spikemonitor_5__source_idx;
extern const int _num__array_spikemonitor_5__source_idx;
extern int32_t *_array_spikemonitor_5_count;
extern const int _num__array_spikemonitor_5_count;
extern int32_t *_array_spikemonitor_5_N;
extern const int _num__array_spikemonitor_5_N;
extern int32_t *_array_spikemonitor__source_idx;
extern const int _num__array_spikemonitor__source_idx;
extern int32_t *_array_spikemonitor_count;
extern const int _num__array_spikemonitor_count;
extern int32_t *_array_spikemonitor_N;
extern const int _num__array_spikemonitor_N;
extern int32_t *_array_synapses_10_N;
extern const int _num__array_synapses_10_N;
extern int32_t *_array_synapses_10_sources;
extern const int _num__array_synapses_10_sources;
extern int32_t *_array_synapses_10_targets;
extern const int _num__array_synapses_10_targets;
extern int32_t *_array_synapses_11_N;
extern const int _num__array_synapses_11_N;
extern int32_t *_array_synapses_11_sources;
extern const int _num__array_synapses_11_sources;
extern int32_t *_array_synapses_11_targets;
extern const int _num__array_synapses_11_targets;
extern int32_t *_array_synapses_12_N;
extern const int _num__array_synapses_12_N;
extern int32_t *_array_synapses_12_sources;
extern const int _num__array_synapses_12_sources;
extern int32_t *_array_synapses_12_targets;
extern const int _num__array_synapses_12_targets;
extern int32_t *_array_synapses_13_N;
extern const int _num__array_synapses_13_N;
extern int32_t *_array_synapses_13_sources;
extern const int _num__array_synapses_13_sources;
extern int32_t *_array_synapses_13_targets;
extern const int _num__array_synapses_13_targets;
extern int32_t *_array_synapses_14_N;
extern const int _num__array_synapses_14_N;
extern int32_t *_array_synapses_14_sources;
extern const int _num__array_synapses_14_sources;
extern int32_t *_array_synapses_14_targets;
extern const int _num__array_synapses_14_targets;
extern int32_t *_array_synapses_15_N;
extern const int _num__array_synapses_15_N;
extern int32_t *_array_synapses_15_sources;
extern const int _num__array_synapses_15_sources;
extern int32_t *_array_synapses_15_targets;
extern const int _num__array_synapses_15_targets;
extern int32_t *_array_synapses_16_N;
extern const int _num__array_synapses_16_N;
extern int32_t *_array_synapses_16_sources;
extern const int _num__array_synapses_16_sources;
extern int32_t *_array_synapses_16_targets;
extern const int _num__array_synapses_16_targets;
extern int32_t *_array_synapses_17_N;
extern const int _num__array_synapses_17_N;
extern int32_t *_array_synapses_17_sources;
extern const int _num__array_synapses_17_sources;
extern int32_t *_array_synapses_17_targets;
extern const int _num__array_synapses_17_targets;
extern int32_t *_array_synapses_18_N;
extern const int _num__array_synapses_18_N;
extern int32_t *_array_synapses_18_sources;
extern const int _num__array_synapses_18_sources;
extern int32_t *_array_synapses_18_targets;
extern const int _num__array_synapses_18_targets;
extern int32_t *_array_synapses_19_N;
extern const int _num__array_synapses_19_N;
extern int32_t *_array_synapses_19_sources;
extern const int _num__array_synapses_19_sources;
extern int32_t *_array_synapses_19_targets;
extern const int _num__array_synapses_19_targets;
extern int32_t *_array_synapses_1_N;
extern const int _num__array_synapses_1_N;
extern int32_t *_array_synapses_1_sources;
extern const int _num__array_synapses_1_sources;
extern int32_t *_array_synapses_1_targets;
extern const int _num__array_synapses_1_targets;
extern int32_t *_array_synapses_20_N;
extern const int _num__array_synapses_20_N;
extern int32_t *_array_synapses_20_sources;
extern const int _num__array_synapses_20_sources;
extern int32_t *_array_synapses_20_targets;
extern const int _num__array_synapses_20_targets;
extern int32_t *_array_synapses_21_N;
extern const int _num__array_synapses_21_N;
extern int32_t *_array_synapses_21_sources;
extern const int _num__array_synapses_21_sources;
extern int32_t *_array_synapses_21_targets;
extern const int _num__array_synapses_21_targets;
extern int32_t *_array_synapses_22_N;
extern const int _num__array_synapses_22_N;
extern int32_t *_array_synapses_22_sources;
extern const int _num__array_synapses_22_sources;
extern int32_t *_array_synapses_22_targets;
extern const int _num__array_synapses_22_targets;
extern int32_t *_array_synapses_23_N;
extern const int _num__array_synapses_23_N;
extern int32_t *_array_synapses_23_sources;
extern const int _num__array_synapses_23_sources;
extern int32_t *_array_synapses_23_targets;
extern const int _num__array_synapses_23_targets;
extern int32_t *_array_synapses_24_N;
extern const int _num__array_synapses_24_N;
extern int32_t *_array_synapses_24_sources;
extern const int _num__array_synapses_24_sources;
extern int32_t *_array_synapses_24_targets;
extern const int _num__array_synapses_24_targets;
extern int32_t *_array_synapses_25_N;
extern const int _num__array_synapses_25_N;
extern int32_t *_array_synapses_25_sources;
extern const int _num__array_synapses_25_sources;
extern int32_t *_array_synapses_25_targets;
extern const int _num__array_synapses_25_targets;
extern int32_t *_array_synapses_26_N;
extern const int _num__array_synapses_26_N;
extern int32_t *_array_synapses_26_sources;
extern const int _num__array_synapses_26_sources;
extern int32_t *_array_synapses_26_targets;
extern const int _num__array_synapses_26_targets;
extern int32_t *_array_synapses_27_N;
extern const int _num__array_synapses_27_N;
extern int32_t *_array_synapses_27_sources;
extern const int _num__array_synapses_27_sources;
extern int32_t *_array_synapses_27_targets;
extern const int _num__array_synapses_27_targets;
extern int32_t *_array_synapses_28_N;
extern const int _num__array_synapses_28_N;
extern int32_t *_array_synapses_28_sources;
extern const int _num__array_synapses_28_sources;
extern int32_t *_array_synapses_28_targets;
extern const int _num__array_synapses_28_targets;
extern int32_t *_array_synapses_29_N;
extern const int _num__array_synapses_29_N;
extern int32_t *_array_synapses_29_sources;
extern const int _num__array_synapses_29_sources;
extern int32_t *_array_synapses_29_targets;
extern const int _num__array_synapses_29_targets;
extern int32_t *_array_synapses_2_N;
extern const int _num__array_synapses_2_N;
extern int32_t *_array_synapses_2_sources;
extern const int _num__array_synapses_2_sources;
extern int32_t *_array_synapses_2_targets;
extern const int _num__array_synapses_2_targets;
extern int32_t *_array_synapses_30_N;
extern const int _num__array_synapses_30_N;
extern int32_t *_array_synapses_30_sources;
extern const int _num__array_synapses_30_sources;
extern int32_t *_array_synapses_30_targets;
extern const int _num__array_synapses_30_targets;
extern int32_t *_array_synapses_31_N;
extern const int _num__array_synapses_31_N;
extern int32_t *_array_synapses_31_sources;
extern const int _num__array_synapses_31_sources;
extern int32_t *_array_synapses_31_targets;
extern const int _num__array_synapses_31_targets;
extern int32_t *_array_synapses_32_N;
extern const int _num__array_synapses_32_N;
extern int32_t *_array_synapses_32_sources;
extern const int _num__array_synapses_32_sources;
extern int32_t *_array_synapses_32_targets;
extern const int _num__array_synapses_32_targets;
extern int32_t *_array_synapses_33_N;
extern const int _num__array_synapses_33_N;
extern int32_t *_array_synapses_33_sources;
extern const int _num__array_synapses_33_sources;
extern int32_t *_array_synapses_33_targets;
extern const int _num__array_synapses_33_targets;
extern int32_t *_array_synapses_34_N;
extern const int _num__array_synapses_34_N;
extern int32_t *_array_synapses_34_sources;
extern const int _num__array_synapses_34_sources;
extern int32_t *_array_synapses_34_targets;
extern const int _num__array_synapses_34_targets;
extern int32_t *_array_synapses_35_N;
extern const int _num__array_synapses_35_N;
extern int32_t *_array_synapses_35_sources;
extern const int _num__array_synapses_35_sources;
extern int32_t *_array_synapses_35_targets;
extern const int _num__array_synapses_35_targets;
extern int32_t *_array_synapses_36_N;
extern const int _num__array_synapses_36_N;
extern int32_t *_array_synapses_36_sources;
extern const int _num__array_synapses_36_sources;
extern int32_t *_array_synapses_36_targets;
extern const int _num__array_synapses_36_targets;
extern int32_t *_array_synapses_37_N;
extern const int _num__array_synapses_37_N;
extern int32_t *_array_synapses_37_sources;
extern const int _num__array_synapses_37_sources;
extern int32_t *_array_synapses_37_targets;
extern const int _num__array_synapses_37_targets;
extern int32_t *_array_synapses_3_N;
extern const int _num__array_synapses_3_N;
extern int32_t *_array_synapses_3_sources;
extern const int _num__array_synapses_3_sources;
extern int32_t *_array_synapses_3_targets;
extern const int _num__array_synapses_3_targets;
extern int32_t *_array_synapses_4_N;
extern const int _num__array_synapses_4_N;
extern int32_t *_array_synapses_4_sources;
extern const int _num__array_synapses_4_sources;
extern int32_t *_array_synapses_4_targets;
extern const int _num__array_synapses_4_targets;
extern int32_t *_array_synapses_5_N;
extern const int _num__array_synapses_5_N;
extern int32_t *_array_synapses_5_sources;
extern const int _num__array_synapses_5_sources;
extern int32_t *_array_synapses_5_targets;
extern const int _num__array_synapses_5_targets;
extern int32_t *_array_synapses_6_N;
extern const int _num__array_synapses_6_N;
extern int32_t *_array_synapses_6_sources;
extern const int _num__array_synapses_6_sources;
extern int32_t *_array_synapses_6_targets;
extern const int _num__array_synapses_6_targets;
extern int32_t *_array_synapses_7_N;
extern const int _num__array_synapses_7_N;
extern int32_t *_array_synapses_7_sources;
extern const int _num__array_synapses_7_sources;
extern int32_t *_array_synapses_7_targets;
extern const int _num__array_synapses_7_targets;
extern int32_t *_array_synapses_8_N;
extern const int _num__array_synapses_8_N;
extern int32_t *_array_synapses_8_sources;
extern const int _num__array_synapses_8_sources;
extern int32_t *_array_synapses_8_targets;
extern const int _num__array_synapses_8_targets;
extern int32_t *_array_synapses_9_N;
extern const int _num__array_synapses_9_N;
extern int32_t *_array_synapses_9_sources;
extern const int _num__array_synapses_9_sources;
extern int32_t *_array_synapses_9_targets;
extern const int _num__array_synapses_9_targets;
extern int32_t *_array_synapses_N;
extern const int _num__array_synapses_N;

//////////////// dynamic arrays 2d /////////

/////////////// static arrays /////////////
extern double *_static_array__array_neurongroup_1_x;
extern const int _num__static_array__array_neurongroup_1_x;
extern double *_static_array__array_neurongroup_1_y;
extern const int _num__static_array__array_neurongroup_1_y;
extern double *_static_array__array_neurongroup_2_x;
extern const int _num__static_array__array_neurongroup_2_x;
extern double *_static_array__array_neurongroup_2_y;
extern const int _num__static_array__array_neurongroup_2_y;
extern double *_static_array__array_neurongroup_3_x;
extern const int _num__static_array__array_neurongroup_3_x;
extern double *_static_array__array_neurongroup_3_y;
extern const int _num__static_array__array_neurongroup_3_y;
extern double *_static_array__array_neurongroup_4_x;
extern const int _num__static_array__array_neurongroup_4_x;
extern double *_static_array__array_neurongroup_4_y;
extern const int _num__static_array__array_neurongroup_4_y;
extern double *_static_array__array_neurongroup_5_x;
extern const int _num__static_array__array_neurongroup_5_x;
extern double *_static_array__array_neurongroup_5_y;
extern const int _num__static_array__array_neurongroup_5_y;
extern double *_static_array__array_neurongroup_x;
extern const int _num__static_array__array_neurongroup_x;
extern double *_static_array__array_neurongroup_y;
extern const int _num__static_array__array_neurongroup_y;
extern int32_t *_static_array__array_synapses_10_sources;
extern const int _num__static_array__array_synapses_10_sources;
extern int32_t *_static_array__array_synapses_10_targets;
extern const int _num__static_array__array_synapses_10_targets;
extern int32_t *_static_array__array_synapses_11_sources;
extern const int _num__static_array__array_synapses_11_sources;
extern int32_t *_static_array__array_synapses_11_targets;
extern const int _num__static_array__array_synapses_11_targets;
extern int32_t *_static_array__array_synapses_12_sources;
extern const int _num__static_array__array_synapses_12_sources;
extern int32_t *_static_array__array_synapses_12_targets;
extern const int _num__static_array__array_synapses_12_targets;
extern int32_t *_static_array__array_synapses_13_sources;
extern const int _num__static_array__array_synapses_13_sources;
extern int32_t *_static_array__array_synapses_13_targets;
extern const int _num__static_array__array_synapses_13_targets;
extern int32_t *_static_array__array_synapses_14_sources;
extern const int _num__static_array__array_synapses_14_sources;
extern int32_t *_static_array__array_synapses_14_targets;
extern const int _num__static_array__array_synapses_14_targets;
extern int32_t *_static_array__array_synapses_15_sources;
extern const int _num__static_array__array_synapses_15_sources;
extern int32_t *_static_array__array_synapses_15_targets;
extern const int _num__static_array__array_synapses_15_targets;
extern int32_t *_static_array__array_synapses_16_sources;
extern const int _num__static_array__array_synapses_16_sources;
extern int32_t *_static_array__array_synapses_16_targets;
extern const int _num__static_array__array_synapses_16_targets;
extern int32_t *_static_array__array_synapses_17_sources;
extern const int _num__static_array__array_synapses_17_sources;
extern int32_t *_static_array__array_synapses_17_targets;
extern const int _num__static_array__array_synapses_17_targets;
extern int32_t *_static_array__array_synapses_18_sources;
extern const int _num__static_array__array_synapses_18_sources;
extern int32_t *_static_array__array_synapses_18_targets;
extern const int _num__static_array__array_synapses_18_targets;
extern int32_t *_static_array__array_synapses_19_sources;
extern const int _num__static_array__array_synapses_19_sources;
extern int32_t *_static_array__array_synapses_19_targets;
extern const int _num__static_array__array_synapses_19_targets;
extern int32_t *_static_array__array_synapses_1_sources;
extern const int _num__static_array__array_synapses_1_sources;
extern int32_t *_static_array__array_synapses_1_targets;
extern const int _num__static_array__array_synapses_1_targets;
extern int32_t *_static_array__array_synapses_20_sources;
extern const int _num__static_array__array_synapses_20_sources;
extern int32_t *_static_array__array_synapses_20_targets;
extern const int _num__static_array__array_synapses_20_targets;
extern int32_t *_static_array__array_synapses_21_sources;
extern const int _num__static_array__array_synapses_21_sources;
extern int32_t *_static_array__array_synapses_21_targets;
extern const int _num__static_array__array_synapses_21_targets;
extern int32_t *_static_array__array_synapses_22_sources;
extern const int _num__static_array__array_synapses_22_sources;
extern int32_t *_static_array__array_synapses_22_targets;
extern const int _num__static_array__array_synapses_22_targets;
extern int32_t *_static_array__array_synapses_23_sources;
extern const int _num__static_array__array_synapses_23_sources;
extern int32_t *_static_array__array_synapses_23_targets;
extern const int _num__static_array__array_synapses_23_targets;
extern int32_t *_static_array__array_synapses_24_sources;
extern const int _num__static_array__array_synapses_24_sources;
extern int32_t *_static_array__array_synapses_24_targets;
extern const int _num__static_array__array_synapses_24_targets;
extern int32_t *_static_array__array_synapses_25_sources;
extern const int _num__static_array__array_synapses_25_sources;
extern int32_t *_static_array__array_synapses_25_targets;
extern const int _num__static_array__array_synapses_25_targets;
extern int32_t *_static_array__array_synapses_26_sources;
extern const int _num__static_array__array_synapses_26_sources;
extern int32_t *_static_array__array_synapses_26_targets;
extern const int _num__static_array__array_synapses_26_targets;
extern int32_t *_static_array__array_synapses_27_sources;
extern const int _num__static_array__array_synapses_27_sources;
extern int32_t *_static_array__array_synapses_27_targets;
extern const int _num__static_array__array_synapses_27_targets;
extern int32_t *_static_array__array_synapses_28_sources;
extern const int _num__static_array__array_synapses_28_sources;
extern int32_t *_static_array__array_synapses_28_targets;
extern const int _num__static_array__array_synapses_28_targets;
extern int32_t *_static_array__array_synapses_29_sources;
extern const int _num__static_array__array_synapses_29_sources;
extern int32_t *_static_array__array_synapses_29_targets;
extern const int _num__static_array__array_synapses_29_targets;
extern int32_t *_static_array__array_synapses_2_sources;
extern const int _num__static_array__array_synapses_2_sources;
extern int32_t *_static_array__array_synapses_2_targets;
extern const int _num__static_array__array_synapses_2_targets;
extern int32_t *_static_array__array_synapses_30_sources;
extern const int _num__static_array__array_synapses_30_sources;
extern int32_t *_static_array__array_synapses_30_targets;
extern const int _num__static_array__array_synapses_30_targets;
extern int32_t *_static_array__array_synapses_31_sources;
extern const int _num__static_array__array_synapses_31_sources;
extern int32_t *_static_array__array_synapses_31_targets;
extern const int _num__static_array__array_synapses_31_targets;
extern int32_t *_static_array__array_synapses_32_sources;
extern const int _num__static_array__array_synapses_32_sources;
extern int32_t *_static_array__array_synapses_32_targets;
extern const int _num__static_array__array_synapses_32_targets;
extern int32_t *_static_array__array_synapses_33_sources;
extern const int _num__static_array__array_synapses_33_sources;
extern int32_t *_static_array__array_synapses_33_targets;
extern const int _num__static_array__array_synapses_33_targets;
extern int32_t *_static_array__array_synapses_34_sources;
extern const int _num__static_array__array_synapses_34_sources;
extern int32_t *_static_array__array_synapses_34_targets;
extern const int _num__static_array__array_synapses_34_targets;
extern int32_t *_static_array__array_synapses_35_sources;
extern const int _num__static_array__array_synapses_35_sources;
extern int32_t *_static_array__array_synapses_35_targets;
extern const int _num__static_array__array_synapses_35_targets;
extern int32_t *_static_array__array_synapses_36_sources;
extern const int _num__static_array__array_synapses_36_sources;
extern int32_t *_static_array__array_synapses_36_targets;
extern const int _num__static_array__array_synapses_36_targets;
extern int32_t *_static_array__array_synapses_37_sources;
extern const int _num__static_array__array_synapses_37_sources;
extern int32_t *_static_array__array_synapses_37_targets;
extern const int _num__static_array__array_synapses_37_targets;
extern int32_t *_static_array__array_synapses_3_sources;
extern const int _num__static_array__array_synapses_3_sources;
extern int32_t *_static_array__array_synapses_3_targets;
extern const int _num__static_array__array_synapses_3_targets;
extern int32_t *_static_array__array_synapses_4_sources;
extern const int _num__static_array__array_synapses_4_sources;
extern int32_t *_static_array__array_synapses_4_targets;
extern const int _num__static_array__array_synapses_4_targets;
extern int32_t *_static_array__array_synapses_5_sources;
extern const int _num__static_array__array_synapses_5_sources;
extern int32_t *_static_array__array_synapses_5_targets;
extern const int _num__static_array__array_synapses_5_targets;
extern int32_t *_static_array__array_synapses_6_sources;
extern const int _num__static_array__array_synapses_6_sources;
extern int32_t *_static_array__array_synapses_6_targets;
extern const int _num__static_array__array_synapses_6_targets;
extern int32_t *_static_array__array_synapses_7_sources;
extern const int _num__static_array__array_synapses_7_sources;
extern int32_t *_static_array__array_synapses_7_targets;
extern const int _num__static_array__array_synapses_7_targets;
extern int32_t *_static_array__array_synapses_8_sources;
extern const int _num__static_array__array_synapses_8_sources;
extern int32_t *_static_array__array_synapses_8_targets;
extern const int _num__static_array__array_synapses_8_targets;
extern int32_t *_static_array__array_synapses_9_sources;
extern const int _num__static_array__array_synapses_9_sources;
extern int32_t *_static_array__array_synapses_9_targets;
extern const int _num__static_array__array_synapses_9_targets;
extern int32_t *_static_array__dynamic_array_spikegeneratorgroup__timebins;
extern const int _num__static_array__dynamic_array_spikegeneratorgroup__timebins;
extern int32_t *_static_array__dynamic_array_spikegeneratorgroup_neuron_index;
extern const int _num__static_array__dynamic_array_spikegeneratorgroup_neuron_index;
extern int32_t *_static_array__dynamic_array_spikegeneratorgroup_spike_number;
extern const int _num__static_array__dynamic_array_spikegeneratorgroup_spike_number;
extern double *_static_array__dynamic_array_spikegeneratorgroup_spike_time;
extern const int _num__static_array__dynamic_array_spikegeneratorgroup_spike_time;

//////////////// synapses /////////////////
// synapses
extern SynapticPathway synapses_pre;
// synapses_1
extern SynapticPathway synapses_1_pre;
// synapses_10
extern SynapticPathway synapses_10_pre;
// synapses_11
extern SynapticPathway synapses_11_pre;
// synapses_12
extern SynapticPathway synapses_12_pre;
// synapses_13
extern SynapticPathway synapses_13_pre;
// synapses_14
extern SynapticPathway synapses_14_pre;
// synapses_15
extern SynapticPathway synapses_15_pre;
// synapses_16
extern SynapticPathway synapses_16_pre;
// synapses_17
extern SynapticPathway synapses_17_pre;
// synapses_18
extern SynapticPathway synapses_18_pre;
// synapses_19
extern SynapticPathway synapses_19_pre;
// synapses_2
extern SynapticPathway synapses_2_pre;
// synapses_20
extern SynapticPathway synapses_20_pre;
// synapses_21
extern SynapticPathway synapses_21_pre;
// synapses_22
extern SynapticPathway synapses_22_pre;
// synapses_23
extern SynapticPathway synapses_23_pre;
// synapses_24
extern SynapticPathway synapses_24_pre;
// synapses_25
extern SynapticPathway synapses_25_pre;
// synapses_26
extern SynapticPathway synapses_26_pre;
// synapses_27
extern SynapticPathway synapses_27_pre;
// synapses_28
extern SynapticPathway synapses_28_pre;
// synapses_29
extern SynapticPathway synapses_29_pre;
// synapses_3
extern SynapticPathway synapses_3_pre;
// synapses_30
extern SynapticPathway synapses_30_pre;
// synapses_31
extern SynapticPathway synapses_31_pre;
// synapses_32
extern SynapticPathway synapses_32_pre;
// synapses_33
extern SynapticPathway synapses_33_pre;
// synapses_34
extern SynapticPathway synapses_34_pre;
// synapses_35
extern SynapticPathway synapses_35_pre;
// synapses_36
extern SynapticPathway synapses_36_pre;
// synapses_37
extern SynapticPathway synapses_37_pre;
// synapses_4
extern SynapticPathway synapses_4_pre;
// synapses_5
extern SynapticPathway synapses_5_pre;
// synapses_6
extern SynapticPathway synapses_6_pre;
// synapses_7
extern SynapticPathway synapses_7_pre;
// synapses_8
extern SynapticPathway synapses_8_pre;
// synapses_9
extern SynapticPathway synapses_9_pre;

// Profiling information for each code object
extern double neurongroup_1_resetter_codeobject_profiling_info;
extern double neurongroup_1_stateupdater_codeobject_profiling_info;
extern double neurongroup_1_thresholder_codeobject_profiling_info;
extern double neurongroup_2_resetter_codeobject_profiling_info;
extern double neurongroup_2_stateupdater_codeobject_profiling_info;
extern double neurongroup_2_thresholder_codeobject_profiling_info;
extern double neurongroup_3_resetter_codeobject_profiling_info;
extern double neurongroup_3_stateupdater_codeobject_profiling_info;
extern double neurongroup_3_thresholder_codeobject_profiling_info;
extern double neurongroup_4_resetter_codeobject_profiling_info;
extern double neurongroup_4_stateupdater_codeobject_profiling_info;
extern double neurongroup_4_thresholder_codeobject_profiling_info;
extern double neurongroup_5_resetter_codeobject_profiling_info;
extern double neurongroup_5_stateupdater_codeobject_profiling_info;
extern double neurongroup_5_thresholder_codeobject_profiling_info;
extern double neurongroup_resetter_codeobject_profiling_info;
extern double neurongroup_thresholder_codeobject_profiling_info;
extern double poissoninput_10_codeobject_profiling_info;
extern double poissoninput_11_codeobject_profiling_info;
extern double poissoninput_12_codeobject_profiling_info;
extern double poissoninput_13_codeobject_profiling_info;
extern double poissoninput_14_codeobject_profiling_info;
extern double poissoninput_15_codeobject_profiling_info;
extern double poissoninput_1_codeobject_profiling_info;
extern double poissoninput_2_codeobject_profiling_info;
extern double poissoninput_3_codeobject_profiling_info;
extern double poissoninput_4_codeobject_profiling_info;
extern double poissoninput_5_codeobject_profiling_info;
extern double poissoninput_6_codeobject_profiling_info;
extern double poissoninput_7_codeobject_profiling_info;
extern double poissoninput_8_codeobject_profiling_info;
extern double poissoninput_9_codeobject_profiling_info;
extern double poissoninput_codeobject_profiling_info;
extern double spikegeneratorgroup_codeobject_profiling_info;
extern double spikemonitor_1_codeobject_profiling_info;
extern double spikemonitor_2_codeobject_profiling_info;
extern double spikemonitor_3_codeobject_profiling_info;
extern double spikemonitor_4_codeobject_profiling_info;
extern double spikemonitor_5_codeobject_profiling_info;
extern double spikemonitor_codeobject_profiling_info;
extern double synapses_10_pre_codeobject_profiling_info;
extern double synapses_10_pre_initialise_queue_profiling_info;
extern double synapses_10_pre_push_spikes_profiling_info;
extern double synapses_11_pre_codeobject_profiling_info;
extern double synapses_11_pre_initialise_queue_profiling_info;
extern double synapses_11_pre_push_spikes_profiling_info;
extern double synapses_12_pre_codeobject_profiling_info;
extern double synapses_12_pre_initialise_queue_profiling_info;
extern double synapses_12_pre_push_spikes_profiling_info;
extern double synapses_13_pre_codeobject_profiling_info;
extern double synapses_13_pre_initialise_queue_profiling_info;
extern double synapses_13_pre_push_spikes_profiling_info;
extern double synapses_14_pre_codeobject_profiling_info;
extern double synapses_14_pre_initialise_queue_profiling_info;
extern double synapses_14_pre_push_spikes_profiling_info;
extern double synapses_15_pre_codeobject_profiling_info;
extern double synapses_15_pre_initialise_queue_profiling_info;
extern double synapses_15_pre_push_spikes_profiling_info;
extern double synapses_16_pre_codeobject_profiling_info;
extern double synapses_16_pre_initialise_queue_profiling_info;
extern double synapses_16_pre_push_spikes_profiling_info;
extern double synapses_17_pre_codeobject_profiling_info;
extern double synapses_17_pre_initialise_queue_profiling_info;
extern double synapses_17_pre_push_spikes_profiling_info;
extern double synapses_18_pre_codeobject_profiling_info;
extern double synapses_18_pre_initialise_queue_profiling_info;
extern double synapses_18_pre_push_spikes_profiling_info;
extern double synapses_19_pre_codeobject_profiling_info;
extern double synapses_19_pre_initialise_queue_profiling_info;
extern double synapses_19_pre_push_spikes_profiling_info;
extern double synapses_1_pre_codeobject_profiling_info;
extern double synapses_1_pre_initialise_queue_profiling_info;
extern double synapses_1_pre_push_spikes_profiling_info;
extern double synapses_20_pre_codeobject_profiling_info;
extern double synapses_20_pre_initialise_queue_profiling_info;
extern double synapses_20_pre_push_spikes_profiling_info;
extern double synapses_21_pre_codeobject_profiling_info;
extern double synapses_21_pre_initialise_queue_profiling_info;
extern double synapses_21_pre_push_spikes_profiling_info;
extern double synapses_22_pre_codeobject_profiling_info;
extern double synapses_22_pre_initialise_queue_profiling_info;
extern double synapses_22_pre_push_spikes_profiling_info;
extern double synapses_23_pre_codeobject_profiling_info;
extern double synapses_23_pre_initialise_queue_profiling_info;
extern double synapses_23_pre_push_spikes_profiling_info;
extern double synapses_24_pre_codeobject_profiling_info;
extern double synapses_24_pre_initialise_queue_profiling_info;
extern double synapses_24_pre_push_spikes_profiling_info;
extern double synapses_25_pre_codeobject_profiling_info;
extern double synapses_25_pre_initialise_queue_profiling_info;
extern double synapses_25_pre_push_spikes_profiling_info;
extern double synapses_26_pre_codeobject_profiling_info;
extern double synapses_26_pre_initialise_queue_profiling_info;
extern double synapses_26_pre_push_spikes_profiling_info;
extern double synapses_27_pre_codeobject_profiling_info;
extern double synapses_27_pre_initialise_queue_profiling_info;
extern double synapses_27_pre_push_spikes_profiling_info;
extern double synapses_28_pre_codeobject_profiling_info;
extern double synapses_28_pre_initialise_queue_profiling_info;
extern double synapses_28_pre_push_spikes_profiling_info;
extern double synapses_29_pre_codeobject_profiling_info;
extern double synapses_29_pre_initialise_queue_profiling_info;
extern double synapses_29_pre_push_spikes_profiling_info;
extern double synapses_2_pre_codeobject_profiling_info;
extern double synapses_2_pre_initialise_queue_profiling_info;
extern double synapses_2_pre_push_spikes_profiling_info;
extern double synapses_30_pre_codeobject_profiling_info;
extern double synapses_30_pre_initialise_queue_profiling_info;
extern double synapses_30_pre_push_spikes_profiling_info;
extern double synapses_31_pre_codeobject_profiling_info;
extern double synapses_31_pre_initialise_queue_profiling_info;
extern double synapses_31_pre_push_spikes_profiling_info;
extern double synapses_32_pre_codeobject_profiling_info;
extern double synapses_32_pre_initialise_queue_profiling_info;
extern double synapses_32_pre_push_spikes_profiling_info;
extern double synapses_33_pre_codeobject_profiling_info;
extern double synapses_33_pre_initialise_queue_profiling_info;
extern double synapses_33_pre_push_spikes_profiling_info;
extern double synapses_34_pre_codeobject_profiling_info;
extern double synapses_34_pre_initialise_queue_profiling_info;
extern double synapses_34_pre_push_spikes_profiling_info;
extern double synapses_35_pre_codeobject_profiling_info;
extern double synapses_35_pre_initialise_queue_profiling_info;
extern double synapses_35_pre_push_spikes_profiling_info;
extern double synapses_36_pre_codeobject_profiling_info;
extern double synapses_36_pre_initialise_queue_profiling_info;
extern double synapses_36_pre_push_spikes_profiling_info;
extern double synapses_37_pre_codeobject_profiling_info;
extern double synapses_37_pre_initialise_queue_profiling_info;
extern double synapses_37_pre_push_spikes_profiling_info;
extern double synapses_3_pre_codeobject_profiling_info;
extern double synapses_3_pre_initialise_queue_profiling_info;
extern double synapses_3_pre_push_spikes_profiling_info;
extern double synapses_4_pre_codeobject_profiling_info;
extern double synapses_4_pre_initialise_queue_profiling_info;
extern double synapses_4_pre_push_spikes_profiling_info;
extern double synapses_5_pre_codeobject_profiling_info;
extern double synapses_5_pre_initialise_queue_profiling_info;
extern double synapses_5_pre_push_spikes_profiling_info;
extern double synapses_6_pre_codeobject_profiling_info;
extern double synapses_6_pre_initialise_queue_profiling_info;
extern double synapses_6_pre_push_spikes_profiling_info;
extern double synapses_7_pre_codeobject_profiling_info;
extern double synapses_7_pre_initialise_queue_profiling_info;
extern double synapses_7_pre_push_spikes_profiling_info;
extern double synapses_8_pre_codeobject_profiling_info;
extern double synapses_8_pre_initialise_queue_profiling_info;
extern double synapses_8_pre_push_spikes_profiling_info;
extern double synapses_9_pre_codeobject_profiling_info;
extern double synapses_9_pre_initialise_queue_profiling_info;
extern double synapses_9_pre_push_spikes_profiling_info;
extern double synapses_pre_codeobject_profiling_info;
extern double synapses_pre_initialise_queue_profiling_info;
extern double synapses_pre_push_spikes_profiling_info;
}

void _init_arrays();
void _load_arrays();
void _write_arrays();
void _dealloc_arrays();

#endif


